### ISSUE TITLE
buster and bookworm have differing gui pixel values for tkinter objects

### ISSUE THREAD

**Issue by kgarwoodsdzwa** [conservationtechlab/dencam#107]
need to add a config file that switches between the pixel placement values for the widgets based on the operating system. can all be checked and called within gui.py

**Comment by iingram** [comment]
I know we talked about storing these values in a CSV file read by `gui.py` but I am wondering, given how intrinsic to the program they are, whether we code them directly into a Python object (maybe a dictionary or dictionary of dictionaries) in their own module file and just import that object into `gui.py` instead of having to read the CSV file?
